### ISSUE TITLE
Cow / Pigs not spawning

### ISSUE THREAD

**Issue by Vyraal1** [AllTheMods/ATM-2#18]
Playing on the official server - it seems other users and myself have noted that cows/pig spawns are rare enough almost to the point of not spawning anymore. I personally have checked areas outside of the pregenned zone or almost untouched (ie sugar cane was still only one block tall). 

Ideas have been thrown around that it might be Animania and BoP conflicting, and Myr has noted that buying any form of animal egg from a Pam's Harvestcraft Market results in the blank default "Spawn" egg. Could possibly be Animania's fault but it is Pam's Harvestcraft we are talking about as well so the issue could be unrelated.

**Comment by OrdinatorStouff** [comment]
I wonder if it's an animania conflict with BoP -- perhaps animania is hardcoded to specific vanilla biomes. If not it sounds like the Animania [spawning is a bit limited](https://github.com/capnkirok/animania/issues/143) in the first place.

Instead of just increasing animania spawn rates (bad idea as those entities are [more](https://github.com/capnkirok/animania/issues/41) [likely](https://github.com/capnkirok/animania/issues/21) [to lag](https://github.com/capnkirok/animania/issues/71) than others) -- As a possible solution it seems the animania config allows vanilla stuff to spawn in addition to special animania mobs. Setting the following to **false** might be a good solution. So that special ones can be found if you want otherwise default mobs are still around too:

```    B:"Enable recipes to exchange special meats for vanilla"=true
    B:"Remove vanilla Chickens"=false
    B:"Remove vanilla Cows"=false
    B:"Remove vanilla Pigs"=false

**Comment by whatthedrunk** [comment]
Changed the config for v0.68 which will be out soon. Let me know if it causes any issues.
