### ISSUE TITLE
RAM issue

### ISSUE THREAD

**Issue by SuperUnitato** [AllTheMods/ATM-2#29]
I haven't seen anything about this, but no matter how much memory I allocate to to the pack (I've done 5gb and 8gb) the ram usage always seems to keep climbing steadily. for example when you log in it starts from 45-60 % (give or take) and over time gradually increases to 80-100% and after a couple hours or so (I haven't timed) I get constant lag spikes because java is trying to do emergency trash collection. Not sure if a mod is causing this or if it's just java but i can't take 5 steps without a lag spike. Re-logging usually fixes it, however sometimes when I try to relog because I'm getting lag spikes, the game crashes upon re-entry.

crash log (I didn't see anything useful but im sure someone will ask for it):
https://gist.github.com/SuperUnitato/0a254bf6f8f978243897e356295c5461

Edit: there are no entities building (mobs, items on the ground, not even Items rendering in pipes)

**Comment by OrdinatorStouff** [comment]
Some steps to try:
1) Install latest 64-bit [JDK](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
2) In curse/twitch app minecraft settings select "Use JAR Launcher"
3) Also in the dropdown for Java version manually select the newly installed "JDK" version from the list _(can see it in the 'path')_
4) Use this additional jav args:
`-server -d64 -Xms2G -XX:+ExplicitGCInvokesConcurrent -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+UseConcMarkSweepGC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:UseSSE=3`


If the problem is still happening with those changes we may need to get more granular with things like profiling to try to find out where all the RAM is going.
